### ISSUE TITLE
realpath: missing operand

### ISSUE THREAD

**Issue by joedborg** [diddledan/one-script-wsl2-systemd#5]
Just ran the install script as the README says, but I think I'm locked out of the VM:

```
realpath: missing operand
Try 'realpath --help' for more information.
[sudo] password for joe:
/bin/sh: 0: Can't open

[process exited with code 127]
```

**Comment by joedborg** [comment]
I believe this is because I have set ZSH as my default shell

**Comment by diddledan** [comment]
Hi, sorry about that. I've included a fix in c7d027a and dfa6d6b. To get back into your distro, run `wsl.exe -d YOUR_DISTRO_NAME rm /etc/profile.d/00-wsl2-systemd` and then rerun the installation script.

**Comment by diddledan** [comment]
Ideally, you shouldn't be accessing `/etc/profile.d/00-wsl2-systemd.sh` from zsh, because this is meant to be a `BASH` script only. zsh is not meant to access any files in `/etc/profile.d` at all. ZSH therefore should have its own initialisation script written along the same lines as the bash one.

**Comment by joedborg** [comment]
The issue is, I can't do anything to the container:

```
➜ wsl.exe -d Ubuntu rm /etc/profile.d/00-wsl2-systemd.sh
realpath: missing operand
Try 'realpath --help' for more information.
[sudo] password for joe:
```

**Comment by diddledan** [comment]
There's another slight modification to the command that you can execute to remove the script:

```bash
wsl -d Ubuntu -e rm /etc/profile.d/00-wsl2-systemd.sh
```

Note the addition of `-e` which will tell `wsl.exe` to not use the default shell at all, but to run the command directly.

**Comment by diddledan** [comment]
If that still fails, you can try using root:

```bash
wsl.exe -d Ubuntu -u root rm /etc/profile.d/00-wsl2-systemd.sh
```

or

```bash
wsl.exe -d Ubuntu -u root -e rm /etc/profile.d/00-wsl2-systemd.sh
```

**Comment by joedborg** [comment]
Thanks, after running it again, it seems to be adding the `-` to the shell name:

```
/etc/profile.d/00-wsl2-systemd.sh:50: command not found: -zsh
```
